/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 forest_loner.glb -s -t --transform
Author: PatricijaKeica (https://sketchfab.com/PatricijaKeica)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dae-diorama-forest-loner-bf8ef1c72740478bbb3d2e125bda70fa
Title: DAE Diorama - Forest Loner
*/

import * as THREE from 'three'
import React, {ForwardedRef, forwardRef, useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    spruce14_treeBranch_0: THREE.Mesh
    spruce14_treeBark_0: THREE.Mesh
    spruce15_treeBranch_0: THREE.Mesh
    spruce15_treeBark_0: THREE.Mesh
    rock14_rocks_0: THREE.Mesh
    pPlane371_treeBranch_0: THREE.Mesh
    pPlane371_treeBark_0: THREE.Mesh
    youngTree8_treeBranch_0: THREE.Mesh
    youngTree8_treeBark_0: THREE.Mesh
    spoon5_seeTrough_dreamcatcher_forks_0: THREE.Mesh
    spoon5_details_0: THREE.Mesh
    pCube1_rocks_0: THREE.Mesh
    fork3_seeTrough_dreamcatcher_forks_0: THREE.Mesh
    fork3_details_0: THREE.Mesh
    pCube131_rocks_0: THREE.Mesh
    spoon2_seeTrough_dreamcatcher_forks_0: THREE.Mesh
    spoon2_details_0: THREE.Mesh
    bottle6_bench_bottle_bucket1_0: THREE.Mesh
    youngTree_treeBranch_0: THREE.Mesh
    youngTree_treeBark_0: THREE.Mesh
    rock18_rocks_0: THREE.Mesh
    pCube135_rocks_0: THREE.Mesh
    frog8_waterlilies_0: THREE.Mesh
    pCube129_lambert1_0: THREE.Mesh
    spruce7_treeBranch_0: THREE.Mesh
    spruce7_treeBark_0: THREE.Mesh
    youngTree5_treeBranch_0: THREE.Mesh
    youngTree5_treeBark_0: THREE.Mesh
    rock8_rocks_0: THREE.Mesh
    youngTree9_treeBranch_0: THREE.Mesh
    youngTree9_treeBark_0: THREE.Mesh
    bonfire_bonfire3_0: THREE.Mesh
    pPlane348_flowerWild2_0: THREE.Mesh
    pPlane338_flowerWild2_0: THREE.Mesh
    pPlane333_flowerWild2_0: THREE.Mesh
    car_car3_0: THREE.Mesh
    car_palette_gastank_watercan3_0: THREE.Mesh
    car_bench_bottle_bucket1_0: THREE.Mesh
    spruce4_treeBranch_0: THREE.Mesh
    spruce4_treeBark_0: THREE.Mesh
    youngTree12_treeBranch_0: THREE.Mesh
    youngTree12_treeBark_0: THREE.Mesh
    youngTree16_treeBranch_0: THREE.Mesh
    youngTree16_treeBark_0: THREE.Mesh
    water1_water_0: THREE.Mesh
    youngTree13_treeBranch_0: THREE.Mesh
    youngTree13_treeBark_0: THREE.Mesh
    rock_rocks_0: THREE.Mesh
    bottle1_bench_bottle_bucket1_0: THREE.Mesh
    Pine3_PineBranchBrown_0: THREE.Mesh
    Pine3_branchPineYellow_0: THREE.Mesh
    Pine3_PineNeedles_0: THREE.Mesh
    Pine3_treeBark_0: THREE.Mesh
    rock10_rocks_0: THREE.Mesh
    pPlane346_flowerWild2_0: THREE.Mesh
    pPlane343_flowerWild2_0: THREE.Mesh
    spruce5f_treeBranch_0: THREE.Mesh
    spruce5f_treeBark_0: THREE.Mesh
    rock15_rocks_0: THREE.Mesh
    bottle4_bench_bottle_bucket1_0: THREE.Mesh
    decor1_details_0: THREE.Mesh
    frog6_frog_0: THREE.Mesh
    spruce9_treeBranch_0: THREE.Mesh
    spruce9_treeBark_0: THREE.Mesh
    cup_details_0: THREE.Mesh
    fork1_seeTrough_dreamcatcher_forks_0: THREE.Mesh
    fork1_details_0: THREE.Mesh
    sauna1_sauna_0: THREE.Mesh
    sauna1_lambert1_0: THREE.Mesh
    sauna1_op_bridges_shed_0: THREE.Mesh
    spruce3_treeBranch_0: THREE.Mesh
    spruce3_treeBark_0: THREE.Mesh
    spoon3_seeTrough_dreamcatcher_forks_0: THREE.Mesh
    spoon3_details_0: THREE.Mesh
    palette208_palette_gastank_watercan3_0: THREE.Mesh
    youngTree3_treeBranch_0: THREE.Mesh
    youngTree3_treeBark_0: THREE.Mesh
    youngTree7_treeBranch_0: THREE.Mesh
    youngTree7_treeBark_0: THREE.Mesh
    rock16_rocks_0: THREE.Mesh
    polySurface244_flowersWild_1_0: THREE.Mesh
    car_bridge_shed1pCube63_walls_0: THREE.Mesh
    pPlane337_flowerWild2_0: THREE.Mesh
    frog2_frog_0: THREE.Mesh
    frog4_frog_0: THREE.Mesh
    pPlane369_treeBranch_0: THREE.Mesh
    pPlane369_treeBark_0: THREE.Mesh
    rock1_rocks_0: THREE.Mesh
    spruce12_treeBranch_0: THREE.Mesh
    spruce12_treeBark_0: THREE.Mesh
    pPlane6_lambert1_0: THREE.Mesh
    gastank1_palette_gastank_watercan3_0: THREE.Mesh
    pPlane344_flowerWild2_0: THREE.Mesh
    pPlane340_flowerWild2_0: THREE.Mesh
    pPlane327_waterlilies_0: THREE.Mesh
    pPlane334_flowerWild2_0: THREE.Mesh
    spruce1_treeBranch_0: THREE.Mesh
    spruce1_treeBark_0: THREE.Mesh
    pPlane345_flowerWild2_0: THREE.Mesh
    spoon6_seeTrough_dreamcatcher_forks_0: THREE.Mesh
    watercan_palette_gastank_watercan3_0: THREE.Mesh
    frog3_frog_0: THREE.Mesh
    palette209_palette_gastank_watercan3_0: THREE.Mesh
    palette1_palette_gastank_watercan3_0: THREE.Mesh
    pCube130_rocks_0: THREE.Mesh
    youngTree15_treeBranch_0: THREE.Mesh
    youngTree15_treeBark_0: THREE.Mesh
    youngTree6_treeBranch_0: THREE.Mesh
    youngTree6_treeBark_0: THREE.Mesh
    spoon4_seeTrough_dreamcatcher_forks_0: THREE.Mesh
    spoon4_details_0: THREE.Mesh
    spruce6_treeBranch_0: THREE.Mesh
    spruce6_treeBark_0: THREE.Mesh
    mainPlain_groundSandGrassMix_0: THREE.Mesh
    mainPlain_groundSand_0: THREE.Mesh
    mainPlain_groundGrass_0: THREE.Mesh
    mainPlain_road_0: THREE.Mesh
    mainPlain_groundGrass2_0: THREE.Mesh
    frog7_frog_0: THREE.Mesh
    youngTree4_treeBranch_0: THREE.Mesh
    youngTree4_treeBark_0: THREE.Mesh
    cup1_details_0: THREE.Mesh
    bottle2_bench_bottle_bucket1_0: THREE.Mesh
    rock6_rocks_0: THREE.Mesh
    pPlane370_treeBranch_0: THREE.Mesh
    pPlane370_treeBark_0: THREE.Mesh
    spoon_seeTrough_dreamcatcher_forks_0: THREE.Mesh
    spoon_details_0: THREE.Mesh
    spoon1_seeTrough_dreamcatcher_forks_0: THREE.Mesh
    spoon1_details_0: THREE.Mesh
    rock5_rocks_0: THREE.Mesh
    spruce_treeBranch_0: THREE.Mesh
    spruce_treeBark_0: THREE.Mesh
    rock9_rocks_0: THREE.Mesh
    youngTree10_treeBranch_0: THREE.Mesh
    youngTree10_treeBark_0: THREE.Mesh
    pPlane328_waterlilies_0: THREE.Mesh
    fork_seeTrough_dreamcatcher_forks_0: THREE.Mesh
    fork_details_0: THREE.Mesh
    pCube16_rocks_0: THREE.Mesh
    pPlane341_flowerWild2_0: THREE.Mesh
    can2_details_0: THREE.Mesh
    bottle3_bench_bottle_bucket1_0: THREE.Mesh
    pCube132_rocks_0: THREE.Mesh
    fork15_seeTrough_dreamcatcher_forks_0: THREE.Mesh
    fork15_details_0: THREE.Mesh
    rock4_rocks_0: THREE.Mesh
    frog5_frog_0: THREE.Mesh
    youngTree11_treeBranch_0: THREE.Mesh
    youngTree11_treeBark_0: THREE.Mesh
    shed_op_bridges_shed_0: THREE.Mesh
    shed_trim_sh_0: THREE.Mesh
    shed_tilable_sh_0: THREE.Mesh
    shed_shedDoors_Windows_0: THREE.Mesh
    shed_shedRoof_0: THREE.Mesh
    shed_shedRoofDetails_0: THREE.Mesh
    pPlane379_treeBranch_0: THREE.Mesh
    pPlane379_treeBark_0: THREE.Mesh
    spruce8_treeBranch_0: THREE.Mesh
    spruce8_treeBark_0: THREE.Mesh
    painting3_painting_0: THREE.Mesh
    youngTree14_treeBranch_0: THREE.Mesh
    youngTree14_treeBark_0: THREE.Mesh
    spruce10_treeBranch_0: THREE.Mesh
    spruce10_treeBark_0: THREE.Mesh
    closet1_ClosetPlants_0: THREE.Mesh
    closet1_ClosetPot_0: THREE.Mesh
    closet1_closet_0: THREE.Mesh
    rock12_rocks_0: THREE.Mesh
    pCube133_rocks_0: THREE.Mesh
    can_details_0: THREE.Mesh
    Pine1_PineBranchBrown_0: THREE.Mesh
    Pine1_branchPineYellow_0: THREE.Mesh
    Pine1_PineNeedles_0: THREE.Mesh
    Pine1_treeBark_0: THREE.Mesh
    spruce11_treeBranch_0: THREE.Mesh
    spruce11_treeBark_0: THREE.Mesh
    pan_details_0: THREE.Mesh
    pPlane332_flowerWild2_0: THREE.Mesh
    rock17_rocks_0: THREE.Mesh
    rock20_rocks_0: THREE.Mesh
    pCube119_frog_0: THREE.Mesh
    rock21_rocks_0: THREE.Mesh
    pine7_PineBranchBrown_0: THREE.Mesh
    pine7_branchPineYellow_0: THREE.Mesh
    pine7_PineNeedles_0: THREE.Mesh
    pine7_treeBark_0: THREE.Mesh
    pine4_branchPineYellow_0: THREE.Mesh
    pine4_PineNeedles_0: THREE.Mesh
    pine4_PineBranchBrown_0: THREE.Mesh
    pine4_treeBark_0: THREE.Mesh
    pPlane331_flowerWild2_0: THREE.Mesh
    bench_bench_bottle_bucket1_0: THREE.Mesh
    fork2_seeTrough_dreamcatcher_forks_0: THREE.Mesh
    fork2_details_0: THREE.Mesh
    rock7_rocks_0: THREE.Mesh
    rock19_rocks_0: THREE.Mesh
    frog1_frog_0: THREE.Mesh
    rock13_rocks_0: THREE.Mesh
    bridge1_op_bridges_shed_0: THREE.Mesh
    bridge1_bridgeWood_0: THREE.Mesh
    bottle5_bench_bottle_bucket1_0: THREE.Mesh
    pPlane339_flowerWild2_0: THREE.Mesh
    rock11_rocks_0: THREE.Mesh
    pPlane336_flowerWild2_0: THREE.Mesh
    pPlane347_flowerWild2_0: THREE.Mesh
    rock3_rocks_0: THREE.Mesh
    spruce13_treeBranch_0: THREE.Mesh
    spruce13_treeBark_0: THREE.Mesh
    rock2_rocks_0: THREE.Mesh
    pPlane335_flowerWild2_0: THREE.Mesh
    house1_decals_house_0: THREE.Mesh
    house1_Housedetails_0: THREE.Mesh
    house1_dock_0: THREE.Mesh
    house1_windows_and_other_0: THREE.Mesh
    house1_behind_0: THREE.Mesh
    house1_walls_0: THREE.Mesh
    house1_lambert1_0: THREE.Mesh
    house1_roof_0: THREE.Mesh
    house1_painting_0: THREE.Mesh
    house1_details_0: THREE.Mesh
    house1_rope_0: THREE.Mesh
    house1_seeTrough_dreamcatcher_forks_0: THREE.Mesh
    house1_fabricAndWood_0: THREE.Mesh
    house1_seetrPlastic_0: THREE.Mesh
    pCube118_frog_0: THREE.Mesh
    pPlane349_flowerWild2_0: THREE.Mesh
    Pine2_PineBranchBrown_0: THREE.Mesh
    Pine2_PineNeedles_0: THREE.Mesh
    Pine2_branchPineYellow_0: THREE.Mesh
    Pine2_treeBark_0: THREE.Mesh
    bridge2_bridgeWood_0: THREE.Mesh
    bridge2_op_bridges_shed_0: THREE.Mesh
    spruce2_treeBranch_0: THREE.Mesh
    spruce2_treeBark_0: THREE.Mesh
    hotTub1_hotTub_0: THREE.Mesh
    pine6_PineBranchBrown_0: THREE.Mesh
    pine6_branchPineYellow_0: THREE.Mesh
    pine6_PineNeedles_0: THREE.Mesh
    pine6_treeBark_0: THREE.Mesh
    plants_flowersWild_1_0: THREE.Mesh
    plants_flowersWild3_0: THREE.Mesh
    plants_treeBranch_0: THREE.Mesh
    plants_treeBark_0: THREE.Mesh
    chair1fork8_painting_0: THREE.Mesh
    chair1pCylinder34_chair1chairAndTable_0: THREE.Mesh
    chair1fork7_painting_0: THREE.Mesh
    chair1fork9_painting_0: THREE.Mesh
    chair1chair_chair1chairAndTable_0: THREE.Mesh
    chair1fork6_painting_0: THREE.Mesh
  }
  materials: {
    treeBranch: THREE.MeshStandardMaterial
    treeBark: THREE.MeshStandardMaterial
    rocks: THREE.MeshStandardMaterial
    seeTrough_dreamcatcher_forks: THREE.MeshStandardMaterial
    details: THREE.MeshStandardMaterial
    bench_bottle_bucket1: THREE.MeshStandardMaterial
    waterlilies: THREE.MeshStandardMaterial
    lambert1: THREE.MeshStandardMaterial
    bonfire3: THREE.MeshStandardMaterial
    flowerWild2: THREE.MeshStandardMaterial
    car3: THREE.MeshStandardMaterial
    palette_gastank_watercan3: THREE.MeshStandardMaterial
    water: THREE.MeshStandardMaterial
    PineBranchBrown: THREE.MeshStandardMaterial
    branchPineYellow: THREE.MeshStandardMaterial
    PineNeedles: THREE.MeshStandardMaterial
    frog: THREE.MeshStandardMaterial
    sauna: THREE.MeshStandardMaterial
    op_bridges_shed: THREE.MeshStandardMaterial
    flowersWild_1: THREE.MeshStandardMaterial
    walls: THREE.MeshStandardMaterial
    groundSandGrassMix: THREE.MeshStandardMaterial
    groundSand: THREE.MeshStandardMaterial
    groundGrass: THREE.MeshStandardMaterial
    road: THREE.MeshStandardMaterial
    groundGrass2: THREE.MeshStandardMaterial
    trim_sh: THREE.MeshStandardMaterial
    tilable_sh: THREE.MeshStandardMaterial
    shedDoors_Windows: THREE.MeshStandardMaterial
    shedRoof: THREE.MeshStandardMaterial
    shedRoofDetails: THREE.MeshStandardMaterial
    painting: THREE.MeshStandardMaterial
    ClosetPlants: THREE.MeshStandardMaterial
    ClosetPot: THREE.MeshStandardMaterial
    closet: THREE.MeshStandardMaterial
    bridgeWood: THREE.MeshStandardMaterial
    decals_house: THREE.MeshStandardMaterial
    Housedetails: THREE.MeshStandardMaterial
    dock: THREE.MeshStandardMaterial
    windows_and_other: THREE.MeshStandardMaterial
    behind: THREE.MeshStandardMaterial
    roof: THREE.MeshStandardMaterial
    rope: THREE.MeshStandardMaterial
    fabricAndWood: THREE.MeshStandardMaterial
    seetrPlastic: THREE.MeshStandardMaterial
    hotTub: THREE.MeshStandardMaterial
    flowersWild3: THREE.MeshStandardMaterial
    chair1chairAndTable: THREE.MeshStandardMaterial
  }
}


import path from "/models/forest_loner-transformed.glb?url";
import {Group} from "three";


export default forwardRef(function Model(props: JSX.IntrinsicElements['group'], ref: ForwardedRef<Group>) {
  const { nodes, materials } = useGLTF(path) as GLTFResult
  return (
    <group ref={ref} {...props} dispose={null}>
      <group scale={0.01}>
        <group position={[-2154.33, 201.22, 0]}>
          <group position={[1002.53, 213.63, 715.16]} rotation={[-0.04, 0.12, 0.48]} scale={0.69}>
            <mesh castShadow receiveShadow geometry={nodes.spruce14_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.spruce14_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[936.27, 125.62, 826.03]} rotation={[0.09, 0.14, 0.56]} scale={1.07}>
            <mesh castShadow receiveShadow geometry={nodes.spruce15_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.spruce15_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[872.49, 64.26, 413.74]} rotation={[-0.13, 0.09, 0.2]}>
            <mesh castShadow receiveShadow geometry={nodes.pPlane371_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.pPlane371_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[1932.75, 245.64, -113.13]} rotation={[0.12, -0.2, -0.12]} scale={0.82}>
            <mesh castShadow receiveShadow geometry={nodes.youngTree8_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.youngTree8_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[2927.87, -43.23, 1004.64]} rotation={[1.68, 0.15, -2.13]} scale={0.26}>
            <mesh castShadow receiveShadow geometry={nodes.spoon5_seeTrough_dreamcatcher_forks_0.geometry} material={materials.seeTrough_dreamcatcher_forks} />
            <mesh castShadow receiveShadow geometry={nodes.spoon5_details_0.geometry} material={materials.details} />
          </group>
          <group position={[2835.41, -76.99, 827.46]} rotation={[1.54, 0.01, 0]} scale={0.3}>
            <mesh castShadow receiveShadow geometry={nodes.fork3_seeTrough_dreamcatcher_forks_0.geometry} material={materials.seeTrough_dreamcatcher_forks} />
            <mesh castShadow receiveShadow geometry={nodes.fork3_details_0.geometry} material={materials.details} />
          </group>
          <group position={[2991.78, 81.82, 626.91]} rotation={[1.78, -0.03, 2.11]} scale={0.26}>
            <mesh castShadow receiveShadow geometry={nodes.spoon2_seeTrough_dreamcatcher_forks_0.geometry} material={materials.seeTrough_dreamcatcher_forks} />
            <mesh castShadow receiveShadow geometry={nodes.spoon2_details_0.geometry} material={materials.details} />
          </group>
          <group position={[1201.13, -226.64, 1107.2]} rotation={[0.58, 0.26, 0.21]} scale={1.25}>
            <mesh castShadow receiveShadow geometry={nodes.youngTree_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.youngTree_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[2168.5, 189.18, -642.24]} rotation={[-0.09, -0.09, -0.08]} scale={0.37}>
            <mesh castShadow receiveShadow geometry={nodes.spruce7_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.spruce7_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[1329.21, 509.19, 671.19]} rotation={[-0.14, -0.24, -0.19]} scale={1.21}>
            <mesh castShadow receiveShadow geometry={nodes.youngTree5_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.youngTree5_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[2617.9, 184.61, -194.53]} rotation={[-0.16, -0.24, -0.19]} scale={0.89}>
            <mesh castShadow receiveShadow geometry={nodes.youngTree9_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.youngTree9_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[1792.05, -268.93, 2375.55]} rotation={[0.1, 1.2, -0.05]}>
            <mesh castShadow receiveShadow geometry={nodes.car_car3_0.geometry} material={materials.car3} />
            <mesh castShadow receiveShadow geometry={nodes.car_palette_gastank_watercan3_0.geometry} material={materials.palette_gastank_watercan3} />
            <mesh castShadow receiveShadow geometry={nodes.car_bench_bottle_bucket1_0.geometry} material={materials.bench_bottle_bucket1} />
          </group>
          <group position={[2611.76, 172.54, 984.82]} rotation={[0.02, -0.09, -0.1]} scale={0.37}>
            <mesh castShadow receiveShadow geometry={nodes.spruce4_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.spruce4_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[2082.3, 158.41, -894.95]} rotation={[-0.23, -0.24, -0.19]} scale={1.02}>
            <mesh castShadow receiveShadow geometry={nodes.youngTree12_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.youngTree12_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[2059.84, 241.84, -268.68]} rotation={[0.12, -0.2, -0.12]} scale={1.09}>
            <mesh castShadow receiveShadow geometry={nodes.youngTree16_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.youngTree16_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[2444.49, 181.82, 724.43]} rotation={[-0.16, -0.24, -0.19]} scale={1.01}>
            <mesh castShadow receiveShadow geometry={nodes.youngTree13_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.youngTree13_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[1886.28, 286.23, 410.5]} rotation={[-2.72, -0.14, 3.03]} scale={0.76}>
            <mesh castShadow receiveShadow geometry={nodes.Pine3_PineBranchBrown_0.geometry} material={materials.PineBranchBrown} />
            <mesh castShadow receiveShadow geometry={nodes.Pine3_branchPineYellow_0.geometry} material={materials.branchPineYellow} />
            <mesh castShadow receiveShadow geometry={nodes.Pine3_PineNeedles_0.geometry} material={materials.PineNeedles} />
            <mesh castShadow receiveShadow geometry={nodes.Pine3_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[2387.08, 133.47, -613.54]} rotation={[0.03, -0.09, 0.04]} scale={0.23}>
            <mesh castShadow receiveShadow geometry={nodes.spruce5f_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.spruce5f_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[1989.92, 183.13, -763.86]} rotation={[-0.37, -0.14, 0.11]} scale={0.34}>
            <mesh castShadow receiveShadow geometry={nodes.spruce9_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.spruce9_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[2764.78, 111.94, 868.06]} rotation={[1.54, 0.01, 0]} scale={0.28}>
            <mesh castShadow receiveShadow geometry={nodes.fork1_seeTrough_dreamcatcher_forks_0.geometry} material={materials.seeTrough_dreamcatcher_forks} />
            <mesh castShadow receiveShadow geometry={nodes.fork1_details_0.geometry} material={materials.details} />
          </group>
          <group position={[1544.31, 23.41, 1033.93]} rotation={[0.64, -0.08, -0.02]} scale={0.28}>
            <mesh castShadow receiveShadow geometry={nodes.spruce3_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.spruce3_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[2692.91, -6.42, 790.17]} rotation={[1.61, -0.22, 0.7]} scale={0.26}>
            <mesh castShadow receiveShadow geometry={nodes.spoon3_seeTrough_dreamcatcher_forks_0.geometry} material={materials.seeTrough_dreamcatcher_forks} />
            <mesh castShadow receiveShadow geometry={nodes.spoon3_details_0.geometry} material={materials.details} />
          </group>
          <group position={[1645.23, 347.31, 641.4]} rotation={[-0.14, -0.24, -0.19]} scale={0.73}>
            <mesh castShadow receiveShadow geometry={nodes.youngTree3_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.youngTree3_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[1996.34, 254.93, 128.81]} rotation={[0.1, -0.24, -0.19]} scale={0.73}>
            <mesh castShadow receiveShadow geometry={nodes.youngTree7_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.youngTree7_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[821.87, 26.04, 32.26]} rotation={[0.18, 0.08, 0.15]}>
            <mesh castShadow receiveShadow geometry={nodes.pPlane369_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.pPlane369_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[1333.61, 257.15, -750.75]} rotation={[-0.09, -0.03, -0.05]} scale={0.27}>
            <mesh castShadow receiveShadow geometry={nodes.spruce12_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.spruce12_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[1889.68, 142.98, 819.94]} rotation={[0.13, -0.08, -0.12]} scale={0.24}>
            <mesh castShadow receiveShadow geometry={nodes.spruce1_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.spruce1_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[2404.69, 218.83, 714.43]} rotation={[-0.16, -0.24, -0.19]} scale={1.41}>
            <mesh castShadow receiveShadow geometry={nodes.youngTree15_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.youngTree15_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[1720.95, 373.94, 504.04]} rotation={[-0.16, -0.63, -0.32]} scale={0.43}>
            <mesh castShadow receiveShadow geometry={nodes.youngTree6_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.youngTree6_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[2753.26, 44.95, 992.17]} rotation={[1.39, -0.08, -0.73]} scale={0.26}>
            <mesh castShadow receiveShadow geometry={nodes.spoon4_seeTrough_dreamcatcher_forks_0.geometry} material={materials.seeTrough_dreamcatcher_forks} />
            <mesh castShadow receiveShadow geometry={nodes.spoon4_details_0.geometry} material={materials.details} />
          </group>
          <group position={[2470.91, 111.67, -743.49]} rotation={[-0.11, -0.1, 0.19]} scale={0.23}>
            <mesh castShadow receiveShadow geometry={nodes.spruce6_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.spruce6_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[2094.66, 0, 0]} scale={1.16}>
            <mesh castShadow receiveShadow geometry={nodes.mainPlain_groundSandGrassMix_0.geometry} material={materials.groundSandGrassMix} />
            <mesh castShadow receiveShadow geometry={nodes.mainPlain_groundSand_0.geometry} material={materials.groundSand} />
            <mesh castShadow receiveShadow geometry={nodes.mainPlain_groundGrass_0.geometry} material={materials.groundGrass} />
            <mesh castShadow receiveShadow geometry={nodes.mainPlain_road_0.geometry} material={materials.road} />
            <mesh castShadow receiveShadow geometry={nodes.mainPlain_groundGrass2_0.geometry} material={materials.groundGrass2} />
          </group>
          <group position={[1662, 375.58, 494.61]} rotation={[-0.56, -0.63, -0.32]} scale={0.43}>
            <mesh castShadow receiveShadow geometry={nodes.youngTree4_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.youngTree4_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[797.4, -1.51, 58.64]} rotation={[-0.2, 0.1, 0.36]}>
            <mesh castShadow receiveShadow geometry={nodes.pPlane370_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.pPlane370_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[2881.75, 30.07, 1013.05]} rotation={[1.66, 0, -1.26]} scale={0.33}>
            <mesh castShadow receiveShadow geometry={nodes.spoon_seeTrough_dreamcatcher_forks_0.geometry} material={materials.seeTrough_dreamcatcher_forks} />
            <mesh castShadow receiveShadow geometry={nodes.spoon_details_0.geometry} material={materials.details} />
          </group>
          <group position={[3177.14, 37.31, 848.68]} rotation={[1.62, 0.17, -2.76]} scale={0.32}>
            <mesh castShadow receiveShadow geometry={nodes.spoon1_seeTrough_dreamcatcher_forks_0.geometry} material={materials.seeTrough_dreamcatcher_forks} />
            <mesh castShadow receiveShadow geometry={nodes.spoon1_details_0.geometry} material={materials.details} />
          </group>
          <group position={[1783.79, 197.1, 710.68]} rotation={[0.05, -0.09, -0.2]} scale={0.4}>
            <mesh castShadow receiveShadow geometry={nodes.spruce_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.spruce_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[2515.67, 175.82, -605.86]} rotation={[0.13, -0.24, -0.19]} scale={1.02}>
            <mesh castShadow receiveShadow geometry={nodes.youngTree10_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.youngTree10_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[2779.57, 21.68, 898.7]} rotation={[1.54, 0.01, 0]} scale={0.24}>
            <mesh castShadow receiveShadow geometry={nodes.fork_seeTrough_dreamcatcher_forks_0.geometry} material={materials.seeTrough_dreamcatcher_forks} />
            <mesh castShadow receiveShadow geometry={nodes.fork_details_0.geometry} material={materials.details} />
          </group>
          <group position={[2772.25, 17.62, 869.99]} rotation={[1.54, 0.01, 0]} scale={0.29}>
            <mesh castShadow receiveShadow geometry={nodes.fork15_seeTrough_dreamcatcher_forks_0.geometry} material={materials.seeTrough_dreamcatcher_forks} />
            <mesh castShadow receiveShadow geometry={nodes.fork15_details_0.geometry} material={materials.details} />
          </group>
          <group position={[2661.81, 301.81, -850.34]} rotation={[-0.37, -0.23, -0.78]} scale={1.02}>
            <mesh castShadow receiveShadow geometry={nodes.youngTree11_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.youngTree11_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[1661.14, 260.9, 437.72]} rotation={[-0.62, -0.63, -0.32]} scale={0.43}>
            <mesh castShadow receiveShadow geometry={nodes.pPlane379_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.pPlane379_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[1833.67, 323.38, -533.87]} rotation={[0.02, -0.09, -0.17]} scale={0.53}>
            <mesh castShadow receiveShadow geometry={nodes.spruce8_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.spruce8_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[2435.44, 39.84, 902.8]} rotation={[0.16, -0.1, 0.1]} scale={0.91}>
            <mesh castShadow receiveShadow geometry={nodes.youngTree14_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.youngTree14_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[1861.36, 278.32, -801.83]} rotation={[-0.6, -0.07, -0.14]} scale={0.26}>
            <mesh castShadow receiveShadow geometry={nodes.spruce10_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.spruce10_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[2497.04, 206.3, -234.08]} rotation={[3.1, 0.97, -3.11]} scale={0.78}>
            <mesh castShadow receiveShadow geometry={nodes.closet1_ClosetPlants_0.geometry} material={materials.ClosetPlants} />
            <mesh castShadow receiveShadow geometry={nodes.closet1_ClosetPot_0.geometry} material={materials.ClosetPot} />
            <mesh castShadow receiveShadow geometry={nodes.closet1_closet_0.geometry} material={materials.closet} />
          </group>
          <group position={[2072.11, -37.54, 1596.35]} rotation={[0.26, 1, -0.22]}>
            <mesh castShadow receiveShadow geometry={nodes.Pine1_PineBranchBrown_0.geometry} material={materials.PineBranchBrown} />
            <mesh castShadow receiveShadow geometry={nodes.Pine1_branchPineYellow_0.geometry} material={materials.branchPineYellow} />
            <mesh castShadow receiveShadow geometry={nodes.Pine1_PineNeedles_0.geometry} material={materials.PineNeedles} />
            <mesh castShadow receiveShadow geometry={nodes.Pine1_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[1711.05, 267.72, -788.71]} rotation={[-0.24, -0.09, -0.1]} scale={0.26}>
            <mesh castShadow receiveShadow geometry={nodes.spruce11_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.spruce11_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[698, -22, 461.31]}>
            <mesh castShadow receiveShadow geometry={nodes.pine7_PineBranchBrown_0.geometry} material={materials.PineBranchBrown} />
            <mesh castShadow receiveShadow geometry={nodes.pine7_branchPineYellow_0.geometry} material={materials.branchPineYellow} />
            <mesh castShadow receiveShadow geometry={nodes.pine7_PineNeedles_0.geometry} material={materials.PineNeedles} />
            <mesh castShadow receiveShadow geometry={nodes.pine7_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[2295.31, 265.74, -170.85]} rotation={[-0.27, 0.99, 0.15]} scale={0.92}>
            <mesh castShadow receiveShadow geometry={nodes.pine4_branchPineYellow_0.geometry} material={materials.branchPineYellow} />
            <mesh castShadow receiveShadow geometry={nodes.pine4_PineNeedles_0.geometry} material={materials.PineNeedles} />
            <mesh castShadow receiveShadow geometry={nodes.pine4_PineBranchBrown_0.geometry} material={materials.PineBranchBrown} />
            <mesh castShadow receiveShadow geometry={nodes.pine4_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[2781.98, -36.65, 826.75]} rotation={[1.54, 0.01, 0]} scale={0.29}>
            <mesh castShadow receiveShadow geometry={nodes.fork2_seeTrough_dreamcatcher_forks_0.geometry} material={materials.seeTrough_dreamcatcher_forks} />
            <mesh castShadow receiveShadow geometry={nodes.fork2_details_0.geometry} material={materials.details} />
          </group>
          <group position={[1040.53, 269.75, -681.12]} rotation={[-0.08, -0.09, -0.06]} scale={0.45}>
            <mesh castShadow receiveShadow geometry={nodes.spruce13_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.spruce13_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[596.85, 148.43, 1269.58]} rotation={[-0.17, -0.02, 0.16]} scale={1.28}>
            <mesh castShadow receiveShadow geometry={nodes.Pine2_PineBranchBrown_0.geometry} material={materials.PineBranchBrown} />
            <mesh castShadow receiveShadow geometry={nodes.Pine2_PineNeedles_0.geometry} material={materials.PineNeedles} />
            <mesh castShadow receiveShadow geometry={nodes.Pine2_branchPineYellow_0.geometry} material={materials.branchPineYellow} />
            <mesh castShadow receiveShadow geometry={nodes.Pine2_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[2213.66, -99.01, -536.02]} rotation={[0.02, -0.43, 0.2]} scale={1.37}>
            <mesh castShadow receiveShadow geometry={nodes.bridge2_bridgeWood_0.geometry} material={materials.bridgeWood} />
            <mesh castShadow receiveShadow geometry={nodes.bridge2_op_bridges_shed_0.geometry} material={materials.op_bridges_shed} />
          </group>
          <group position={[1658.33, 367.65, 879.62]} rotation={[0.22, -0.11, -0.38]} scale={0.27}>
            <mesh castShadow receiveShadow geometry={nodes.spruce2_treeBranch_0.geometry} material={materials.treeBranch} />
            <mesh castShadow receiveShadow geometry={nodes.spruce2_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <group position={[2336.85, 185.64, -304.99]} rotation={[0.11, 0.99, -0.26]} scale={0.7}>
            <mesh castShadow receiveShadow geometry={nodes.pine6_PineBranchBrown_0.geometry} material={materials.PineBranchBrown} />
            <mesh castShadow receiveShadow geometry={nodes.pine6_branchPineYellow_0.geometry} material={materials.branchPineYellow} />
            <mesh castShadow receiveShadow geometry={nodes.pine6_PineNeedles_0.geometry} material={materials.PineNeedles} />
            <mesh castShadow receiveShadow geometry={nodes.pine6_treeBark_0.geometry} material={materials.treeBark} />
          </group>
          <mesh castShadow receiveShadow geometry={nodes.rock14_rocks_0.geometry} material={materials.rocks} position={[2218.18, 128.2, 202.56]} rotation={[0.48, 0.01, 0.02]} scale={0.52} />
          <mesh castShadow receiveShadow geometry={nodes.pCube1_rocks_0.geometry} material={materials.rocks} position={[2934.14, 129.11, -853.92]} rotation={[0.45, -0.02, 0.11]} scale={0.79} />
          <mesh castShadow receiveShadow geometry={nodes.pCube131_rocks_0.geometry} material={materials.rocks} position={[1824.37, 174.21, 453.34]} rotation={[-0.09, 0.96, -1.23]} />
          <mesh castShadow receiveShadow geometry={nodes.bottle6_bench_bottle_bucket1_0.geometry} material={materials.bench_bottle_bucket1} position={[1845.31, 268.5, 210.87]} rotation={[-0.01, -0.01, -0.01]} scale={0.83} />
          <mesh castShadow receiveShadow geometry={nodes.rock18_rocks_0.geometry} material={materials.rocks} position={[2143.48, 111.45, 406.81]} rotation={[3.11, 0.8, -3.01]} scale={0.23} />
          <mesh castShadow receiveShadow geometry={nodes.pCube135_rocks_0.geometry} material={materials.rocks} position={[2968.11, 112.29, 856.76]} rotation={[0.19, 0.53, 0.68]} scale={0.27} />
          <mesh castShadow receiveShadow geometry={nodes.frog8_waterlilies_0.geometry} material={materials.waterlilies} position={[2372.13, 61.47, 542.45]} rotation={[-0.03, 0.61, -0.01]} scale={1.21} />
          <mesh castShadow receiveShadow geometry={nodes.pCube129_lambert1_0.geometry} material={materials.lambert1} position={[2452.91, 329.41, -142.4]} />
          <mesh castShadow receiveShadow geometry={nodes.rock8_rocks_0.geometry} material={materials.rocks} position={[2068.41, 89.62, 823.26]} rotation={[-2.78, 0.73, -3.08]} />
          <mesh castShadow receiveShadow geometry={nodes.bonfire_bonfire3_0.geometry} material={materials.bonfire3} position={[2526.54, -62.11, 735.17]} rotation={[0, -0.09, 0]} />
          <mesh castShadow receiveShadow geometry={nodes.pPlane348_flowerWild2_0.geometry} material={materials.flowerWild2} position={[1845.51, 155.77, 851.32]} rotation={[1.45, 0.02, 0.67]} scale={0.71} />
          <mesh castShadow receiveShadow geometry={nodes.pPlane338_flowerWild2_0.geometry} material={materials.flowerWild2} position={[2376.7, 99.33, 410.22]} rotation={[1.69, -0.03, -0.51]} scale={0.71} />
          <mesh castShadow receiveShadow geometry={nodes.pPlane333_flowerWild2_0.geometry} material={materials.flowerWild2} position={[2758.76, 146.35, 114.42]} rotation={[1.69, -0.03, -0.51]} scale={0.56} />
          <mesh castShadow receiveShadow geometry={nodes.water1_water_0.geometry} material={materials.water} position={[2391.93, 56.79, 521.14]} rotation={[0.01, -0.68, 0.01]} />
          <mesh castShadow receiveShadow geometry={nodes.rock_rocks_0.geometry} material={materials.rocks} position={[3051.82, 92.96, 186.42]} rotation={[-0.8, 0.03, -0.03]} scale={0.53} />
          <mesh castShadow receiveShadow geometry={nodes.bottle1_bench_bottle_bucket1_0.geometry} material={materials.bench_bottle_bucket1} position={[2498.62, 77.29, 729]} rotation={[-0.1, -0.01, 0.1]} scale={0.83} />
          <mesh castShadow receiveShadow geometry={nodes.rock10_rocks_0.geometry} material={materials.rocks} position={[2016.01, 95.04, 823.26]} rotation={[0.25, 0.51, -0.12]} scale={1.28} />
          <mesh castShadow receiveShadow geometry={nodes.pPlane346_flowerWild2_0.geometry} material={materials.flowerWild2} position={[2045.33, 167.18, 781]} rotation={[1.33, 0.01, 0.63]} scale={0.71} />
          <mesh castShadow receiveShadow geometry={nodes.pPlane343_flowerWild2_0.geometry} material={materials.flowerWild2} position={[2322.95, 126.02, 430.33]} rotation={[1.5, -0.17, -0.86]} scale={0.88} />
          <mesh castShadow receiveShadow geometry={nodes.rock15_rocks_0.geometry} material={materials.rocks} position={[2080.21, 130.33, 228.54]} rotation={[0.4, 0.68, 0.02]} scale={0.41} />
          <mesh castShadow receiveShadow geometry={nodes.bottle4_bench_bottle_bucket1_0.geometry} material={materials.bench_bottle_bucket1} position={[2686.56, 101.98, 792.15]} rotation={[-Math.PI, Math.PI / 9, -Math.PI]} scale={0.83} />
          <mesh castShadow receiveShadow geometry={nodes.decor1_details_0.geometry} material={materials.details} position={[2937, 364.18, 844.44]} rotation={[-0.32, 0.29, 1.63]} scale={[0.55, 0.5, 0.5]} />
          <mesh castShadow receiveShadow geometry={nodes.frog6_frog_0.geometry} material={materials.frog} position={[1910.12, -123.13, 936.6]} rotation={[1.04, 0.94, -0.56]} scale={0.36} />
          <mesh castShadow receiveShadow geometry={nodes.cup_details_0.geometry} material={materials.details} position={[3351.44, 426.45, 848.66]} rotation={[1.93, 1.37, 3.05]} scale={0.41} />
          <mesh castShadow receiveShadow geometry={nodes.sauna1_sauna_0.geometry} material={materials.sauna} />
          <mesh castShadow receiveShadow geometry={nodes.sauna1_lambert1_0.geometry} material={materials.lambert1} />
          <mesh castShadow receiveShadow geometry={nodes.sauna1_op_bridges_shed_0.geometry} material={materials.op_bridges_shed} />
          <mesh castShadow receiveShadow geometry={nodes.palette208_palette_gastank_watercan3_0.geometry} material={materials.palette_gastank_watercan3} position={[3350.14, -280.92, 2674.04]} rotation={[-2.02, 1.46, 2.09]} />
          <mesh castShadow receiveShadow geometry={nodes.rock16_rocks_0.geometry} material={materials.rocks} position={[2116.75, 127.85, 228.54]} rotation={[-2.65, 1.4, 3.06]} scale={0.49} />
          <mesh castShadow receiveShadow geometry={nodes.polySurface244_flowersWild_1_0.geometry} material={materials.flowersWild_1} position={[2635.03, 151.73, 160.83]} rotation={[2.99, 0.32, -1.4]} />
          <mesh castShadow receiveShadow geometry={nodes.car_bridge_shed1pCube63_walls_0.geometry} material={materials.walls} position={[1577.8, 441.97, 494.95]} rotation={[-1.47, -0.06, 0.02]} scale={[1.21, 0.89, 0.86]} />
          <mesh castShadow receiveShadow geometry={nodes.pPlane337_flowerWild2_0.geometry} material={materials.flowerWild2} position={[2723.63, 124.41, 332.12]} rotation={[1.61, 0.07, 3.05]} scale={0.68} />
          <mesh castShadow receiveShadow geometry={nodes.frog2_frog_0.geometry} material={materials.frog} position={[-168.61, -3.93, 31.29]} />
          <mesh castShadow receiveShadow geometry={nodes.frog4_frog_0.geometry} material={materials.frog} position={[2975.96, 20.65, -665.87]} rotation={[0.52, -1.46, 0.6]} scale={0.36} />
          <mesh castShadow receiveShadow geometry={nodes.rock1_rocks_0.geometry} material={materials.rocks} position={[2979.03, 81.46, 188.95]} rotation={[-0.43, 0.76, -0.05]} scale={0.51} />
          <mesh castShadow receiveShadow geometry={nodes.pPlane6_lambert1_0.geometry} material={materials.lambert1} position={[1728.52, 497.95, 192.91]} rotation={[0.52, -0.25, -1.65]} />
          <mesh castShadow receiveShadow geometry={nodes.gastank1_palette_gastank_watercan3_0.geometry} material={materials.palette_gastank_watercan3} position={[2036.02, 286.56, -163.99]} rotation={[1.97, 0.25, -1.36]} scale={1.15} />
          <mesh castShadow receiveShadow geometry={nodes.pPlane344_flowerWild2_0.geometry} material={materials.flowerWild2} position={[2211.12, 88.22, 769.5]} rotation={[1.56, 0.04, -1.47]} scale={0.71} />
          <mesh castShadow receiveShadow geometry={nodes.pPlane340_flowerWild2_0.geometry} material={materials.flowerWild2} position={[2274.56, 130.77, 523.5]} rotation={[1.79, -0.14, -1.44]} scale={0.71} />
          <mesh castShadow receiveShadow geometry={nodes.pPlane327_waterlilies_0.geometry} material={materials.waterlilies} position={[2877.34, 87.82, 210.26]} rotation={[0.01, -1.34, -0.02]} scale={1.29} />
          <mesh castShadow receiveShadow geometry={nodes.pPlane334_flowerWild2_0.geometry} material={materials.flowerWild2} position={[3004.17, 149.9, 106.8]} rotation={[1.42, 0.01, -0.5]} scale={0.63} />
          <mesh castShadow receiveShadow geometry={nodes.pPlane345_flowerWild2_0.geometry} material={materials.flowerWild2} position={[1956.01, 153.73, 809.69]} rotation={[1.44, 0.09, -0.42]} scale={0.71} />
          <mesh castShadow receiveShadow geometry={nodes.spoon6_seeTrough_dreamcatcher_forks_0.geometry} material={materials.seeTrough_dreamcatcher_forks} position={[2776.64, -2.54, 929.1]} rotation={[1.28, 0.01, 0]} scale={0.33} />
          <mesh castShadow receiveShadow geometry={nodes.watercan_palette_gastank_watercan3_0.geometry} material={materials.palette_gastank_watercan3} position={[2156.15, 299.6, -48.15]} rotation={[-3.08, 0.03, -3.11]} scale={0.51} />
          <mesh castShadow receiveShadow geometry={nodes.frog3_frog_0.geometry} material={materials.frog} position={[1992.69, 12.15, 184.01]} rotation={[0.03, 0.16, 0.09]} scale={0.36} />
          <mesh castShadow receiveShadow geometry={nodes.palette209_palette_gastank_watercan3_0.geometry} material={materials.palette_gastank_watercan3} position={[4650.09, -244.81, 2034.68]} rotation={[-2.97, 0.99, 3.06]} />
          <mesh castShadow receiveShadow geometry={nodes.palette1_palette_gastank_watercan3_0.geometry} material={materials.palette_gastank_watercan3} position={[27.63, -271.28, 331.28]} rotation={[-0.12, 0, 0.06]} />
          <mesh castShadow receiveShadow geometry={nodes.pCube130_rocks_0.geometry} material={materials.rocks} position={[1898.5, 167.06, 485.99]} rotation={[-0.32, 0.8, -0.48]} scale={1.31} />
          <mesh castShadow receiveShadow geometry={nodes.frog7_frog_0.geometry} material={materials.frog} position={[1865.08, 223.29, -168.72]} rotation={[-0.05, -0.48, -0.21]} scale={0.36} />
          <mesh castShadow receiveShadow geometry={nodes.cup1_details_0.geometry} material={materials.details} position={[2657.83, 466.75, 1123.86]} rotation={[-0.12, -0.24, -0.95]} scale={0.41} />
          <mesh castShadow receiveShadow geometry={nodes.bottle2_bench_bottle_bucket1_0.geometry} material={materials.bench_bottle_bucket1} position={[2476.31, 71.49, 728.12]} rotation={[1.38, 0.1, -0.6]} scale={0.83} />
          <mesh castShadow receiveShadow geometry={nodes.rock6_rocks_0.geometry} material={materials.rocks} position={[2596.99, 52.65, 256.84]} rotation={[-0.27, 1.33, 0.3]} />
          <mesh castShadow receiveShadow geometry={nodes.rock5_rocks_0.geometry} material={materials.rocks} position={[2596.99, 59.98, 294.76]} rotation={[0.02, 0, 0.07]} />
          <mesh castShadow receiveShadow geometry={nodes.rock9_rocks_0.geometry} material={materials.rocks} position={[1896.38, 102.89, 860.35]} rotation={[-2.55, 0.23, -2.8]} />
          <mesh castShadow receiveShadow geometry={nodes.pPlane328_waterlilies_0.geometry} material={materials.waterlilies} position={[2732.35, 85.86, 217.68]} rotation={[-0.03, 0.61, -0.01]} />
          <mesh castShadow receiveShadow geometry={nodes.pCube16_rocks_0.geometry} material={materials.rocks} position={[2163.23, 131.58, 232.83]} rotation={[0.63, 0.69, 0.06]} scale={0.92} />
          <mesh castShadow receiveShadow geometry={nodes.pPlane341_flowerWild2_0.geometry} material={materials.flowerWild2} position={[2254.5, 80.25, 627.41]} rotation={[1.76, -0.18, -0.36]} scale={0.71} />
          <mesh castShadow receiveShadow geometry={nodes.can2_details_0.geometry} material={materials.details} position={[2903.99, 130.26, -500.16]} rotation={[0.37, -0.68, -1.42]} scale={[0.41, 0.52, 0.41]} />
          <mesh castShadow receiveShadow geometry={nodes.bottle3_bench_bottle_bucket1_0.geometry} material={materials.bench_bottle_bucket1} position={[2702.61, 106.48, 768.74]} rotation={[-Math.PI, 1.48, -Math.PI]} scale={0.83} />
          <mesh castShadow receiveShadow geometry={nodes.pCube132_rocks_0.geometry} material={materials.rocks} position={[2921.78, 140.86, -754.44]} rotation={[-0.85, 0.04, -0.03]} scale={0.55} />
          <mesh castShadow receiveShadow geometry={nodes.rock4_rocks_0.geometry} material={materials.rocks} position={[2970.66, 73.82, 292.51]} rotation={[2.35, -0.23, 1.73]} scale={0.36} />
          <mesh castShadow receiveShadow geometry={nodes.frog5_frog_0.geometry} material={materials.frog} position={[1701.3, 203.92, 800.79]} rotation={[0.06, 0.71, -0.18]} scale={0.36} />
          <mesh castShadow receiveShadow geometry={nodes.shed_op_bridges_shed_0.geometry} material={materials.op_bridges_shed} />
          <mesh castShadow receiveShadow geometry={nodes.shed_trim_sh_0.geometry} material={materials.trim_sh} />
          <mesh castShadow receiveShadow geometry={nodes.shed_tilable_sh_0.geometry} material={materials.tilable_sh} />
          <mesh castShadow receiveShadow geometry={nodes.shed_shedDoors_Windows_0.geometry} material={materials.shedDoors_Windows} />
          <mesh castShadow receiveShadow geometry={nodes.shed_shedRoof_0.geometry} material={materials.shedRoof} />
          <mesh castShadow receiveShadow geometry={nodes.shed_shedRoofDetails_0.geometry} material={materials.shedRoofDetails} />
          <mesh castShadow receiveShadow geometry={nodes.painting3_painting_0.geometry} material={materials.painting} position={[2823.8, 240.36, -352.87]} rotation={[0.33, 0.06, -0.11]} scale={0.85} />
          <mesh castShadow receiveShadow geometry={nodes.rock12_rocks_0.geometry} material={materials.rocks} position={[2519.8, 137.3, -86.64]} rotation={[0.64, 0.89, -0.77]} scale={0.54} />
          <mesh castShadow receiveShadow geometry={nodes.pCube133_rocks_0.geometry} material={materials.rocks} position={[2976.95, 126.9, -782.92]} rotation={[-0.51, 0.09, -2.83]} scale={0.4} />
          <mesh castShadow receiveShadow geometry={nodes.can_details_0.geometry} material={materials.details} position={[2521.89, 79.65, 367]} rotation={[-0.24, -0.29, -1.37]} scale={[0.41, 0.52, 0.41]} />
          <mesh castShadow receiveShadow geometry={nodes.pan_details_0.geometry} material={materials.details} position={[2797.04, 491.94, 391.41]} rotation={[2.89, -0.27, 1.52]} scale={0.5} />
          <mesh castShadow receiveShadow geometry={nodes.pPlane332_flowerWild2_0.geometry} material={materials.flowerWild2} position={[2706.74, 139.7, 124.37]} rotation={[1.35, 0.02, -0.5]} scale={0.69} />
          <mesh castShadow receiveShadow geometry={nodes.rock17_rocks_0.geometry} material={materials.rocks} position={[2080.21, 119.91, 351.2]} rotation={[-0.31, 1.5, 0.22]} scale={0.31} />
          <mesh castShadow receiveShadow geometry={nodes.rock20_rocks_0.geometry} material={materials.rocks} position={[1346.46, 83.12, 876.5]} rotation={[-0.6, 0.75, 0.25]} scale={0.53} />
          <mesh castShadow receiveShadow geometry={nodes.pCube119_frog_0.geometry} material={materials.frog} position={[2222.41, 195.53, 1366.62]} rotation={[0.94, 1.51, -1.1]} scale={0.36} />
          <mesh castShadow receiveShadow geometry={nodes.rock21_rocks_0.geometry} material={materials.rocks} position={[1151.33, 104.68, 390.62]} rotation={[-0.84, -0.92, -0.72]} scale={0.53} />
          <mesh castShadow receiveShadow geometry={nodes.pPlane331_flowerWild2_0.geometry} material={materials.flowerWild2} position={[2668.32, 158.67, 170.89]} rotation={[1.74, -0.04, -0.51]} scale={0.88} />
          <mesh castShadow receiveShadow geometry={nodes.bench_bench_bottle_bucket1_0.geometry} material={materials.bench_bottle_bucket1} position={[2658.64, 84.05, 449.49]} rotation={[-0.67, 1.35, 0.67]} />
          <mesh castShadow receiveShadow geometry={nodes.rock7_rocks_0.geometry} material={materials.rocks} position={[2299.43, 29.86, 789.6]} rotation={[-2.88, 1.27, 2.9]} scale={1.58} />
          <mesh castShadow receiveShadow geometry={nodes.rock19_rocks_0.geometry} material={materials.rocks} position={[1186.2, 233.95, 783.46]} rotation={[-0.84, -0.92, -0.72]} scale={0.53} />
          <mesh castShadow receiveShadow geometry={nodes.frog1_frog_0.geometry} material={materials.frog} position={[2305.78, -128.56, 1633.79]} rotation={[2.61, 1.24, -2.34]} scale={0.36} />
          <mesh castShadow receiveShadow geometry={nodes.rock13_rocks_0.geometry} material={materials.rocks} position={[2493.73, 149.35, -44.06]} rotation={[0, 0, -0.48]} scale={0.65} />
          <mesh castShadow receiveShadow geometry={nodes.bridge1_op_bridges_shed_0.geometry} material={materials.op_bridges_shed} />
          <mesh castShadow receiveShadow geometry={nodes.bridge1_bridgeWood_0.geometry} material={materials.bridgeWood} />
          <mesh castShadow receiveShadow geometry={nodes.bottle5_bench_bottle_bucket1_0.geometry} material={materials.bench_bottle_bucket1} position={[2706.53, 99.64, 792.15]} rotation={[-1.53, -0.04, 2.79]} scale={0.83} />
          <mesh castShadow receiveShadow geometry={nodes.pPlane339_flowerWild2_0.geometry} material={materials.flowerWild2} position={[2441.36, 105.39, 329.53]} rotation={[1.29, -0.16, -0.99]} scale={0.71} />
          <mesh castShadow receiveShadow geometry={nodes.rock11_rocks_0.geometry} material={materials.rocks} position={[3008.84, 52.75, 212.93]} rotation={[-2.78, 0.73, -3.08]} scale={1.38} />
          <mesh castShadow receiveShadow geometry={nodes.pPlane336_flowerWild2_0.geometry} material={materials.flowerWild2} position={[2822.3, 122.55, 311.24]} rotation={[1.58, 0.07, 3.05]} scale={0.64} />
          <mesh castShadow receiveShadow geometry={nodes.pPlane347_flowerWild2_0.geometry} material={materials.flowerWild2} position={[2026.12, 184.55, 790]} rotation={[1.35, -0.12, 1.68]} scale={0.71} />
          <mesh castShadow receiveShadow geometry={nodes.rock3_rocks_0.geometry} material={materials.rocks} position={[2983.99, 73.82, 350.69]} rotation={[-0.9, -0.42, -1.74]} scale={0.54} />
          <mesh castShadow receiveShadow geometry={nodes.rock2_rocks_0.geometry} material={materials.rocks} position={[2906.36, 81.46, 309.55]} rotation={[-2.88, -0.86, 3.05]} scale={0.51} />
          <mesh castShadow receiveShadow geometry={nodes.pPlane335_flowerWild2_0.geometry} material={materials.flowerWild2} position={[2922.19, 147.34, 359.78]} rotation={[1.59, 0.14, 3.05]} scale={0.65} />
          <mesh castShadow receiveShadow geometry={nodes.house1_decals_house_0.geometry} material={materials.decals_house} />
          <mesh castShadow receiveShadow geometry={nodes.house1_Housedetails_0.geometry} material={materials.Housedetails} />
          <mesh castShadow receiveShadow geometry={nodes.house1_dock_0.geometry} material={materials.dock} />
          <mesh castShadow receiveShadow geometry={nodes.house1_windows_and_other_0.geometry} material={materials.windows_and_other} />
          <mesh castShadow receiveShadow geometry={nodes.house1_behind_0.geometry} material={materials.behind} />
          <mesh castShadow receiveShadow geometry={nodes.house1_walls_0.geometry} material={materials.walls} />
          <mesh castShadow receiveShadow geometry={nodes.house1_lambert1_0.geometry} material={materials.lambert1} />
          <mesh castShadow receiveShadow geometry={nodes.house1_roof_0.geometry} material={materials.roof} />
          <mesh castShadow receiveShadow geometry={nodes.house1_painting_0.geometry} material={materials.painting} />
          <mesh castShadow receiveShadow geometry={nodes.house1_details_0.geometry} material={materials.details} />
          <mesh castShadow receiveShadow geometry={nodes.house1_rope_0.geometry} material={materials.rope} />
          <mesh castShadow receiveShadow geometry={nodes.house1_seeTrough_dreamcatcher_forks_0.geometry} material={materials.seeTrough_dreamcatcher_forks} />
          <mesh castShadow receiveShadow geometry={nodes.house1_fabricAndWood_0.geometry} material={materials.fabricAndWood} />
          <mesh castShadow receiveShadow geometry={nodes.house1_seetrPlastic_0.geometry} material={materials.seetrPlastic} />
          <mesh castShadow receiveShadow geometry={nodes.pCube118_frog_0.geometry} material={materials.frog} position={[1517.48, 127.32, 346.13]} rotation={[0.06, -0.01, -0.13]} scale={0.36} />
          <mesh castShadow receiveShadow geometry={nodes.pPlane349_flowerWild2_0.geometry} material={materials.flowerWild2} position={[2364.87, 90.17, 759.68]} rotation={[1.33, 0.01, 0.63]} scale={0.71} />
          <mesh castShadow receiveShadow geometry={nodes.hotTub1_hotTub_0.geometry} material={materials.hotTub} position={[-566.52, -74.41, 22.03]} scale={1.29} />
        </group>
        <group position={[-2154.33, 201.22, 0]}>
          <mesh castShadow receiveShadow geometry={nodes.chair1fork8_painting_0.geometry} material={materials.painting} position={[1677.96, 658.72, -107.97]} rotation={[-0.84, 1.44, 0.85]} scale={0.54} />
          <mesh castShadow receiveShadow geometry={nodes.chair1pCylinder34_chair1chairAndTable_0.geometry} material={materials.chair1chairAndTable} position={[1143.49, 654.22, -663.59]} rotation={[0, -1.54, 0]} scale={0.71} />
          <mesh castShadow receiveShadow geometry={nodes.chair1fork7_painting_0.geometry} material={materials.painting} position={[1728.78, 660.05, -139.73]} scale={0.54} />
          <mesh castShadow receiveShadow geometry={nodes.chair1fork9_painting_0.geometry} material={materials.painting} position={[1612.97, 656.46, 5.27]} rotation={[-3.12, 0.1, 3.13]} scale={0.44} />
          <mesh castShadow receiveShadow geometry={nodes.chair1chair_chair1chairAndTable_0.geometry} material={materials.chair1chairAndTable} position={[1672.55, 652.09, 670.55]} rotation={[0, 0.82, 0]} scale={0.79} />
          <mesh castShadow receiveShadow geometry={nodes.chair1fork6_painting_0.geometry} material={materials.painting} position={[1601.59, 718.77, -95.9]} rotation={[-0.01, 0.62, 0.01]} scale={0.36} />
        </group>
        <mesh castShadow receiveShadow geometry={nodes.plants_flowersWild_1_0.geometry} material={materials.flowersWild_1} />
        <mesh castShadow receiveShadow geometry={nodes.plants_flowersWild3_0.geometry} material={materials.flowersWild3} />
        <mesh castShadow receiveShadow geometry={nodes.plants_treeBranch_0.geometry} material={materials.treeBranch} />
        <mesh castShadow receiveShadow geometry={nodes.plants_treeBark_0.geometry} material={materials.treeBark} />
      </group>
    </group>
  )
})

useGLTF.preload(path);
