/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 free_fire_clocktower_freefire.glb -s -t -T
Author: FFXAN (https://sketchfab.com/FFXAN)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-fire-clocktower-freefire-a4e26a539a6a425fb837238656d152cd
Title: FREE FIRE CLOCKTOWER FREEFIRE
*/

import * as THREE from 'three'
import React, {ForwardedRef, forwardRef, useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16: THREE.Mesh
    Object_18: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_30: THREE.Mesh
    Object_32: THREE.Mesh
    Object_34: THREE.Mesh
    Object_36: THREE.Mesh
    Object_38: THREE.Mesh
    Object_40: THREE.Mesh
    Object_42: THREE.Mesh
    Object_44: THREE.Mesh
    Object_46: THREE.Mesh
    Object_48: THREE.Mesh
    Object_50: THREE.Mesh
    Object_52: THREE.Mesh
    Object_54: THREE.Mesh
    Object_56: THREE.Mesh
    Object_58: THREE.Mesh
    Object_60: THREE.Mesh
    Object_62: THREE.Mesh
    Object_64: THREE.Mesh
    Object_66: THREE.Mesh
    Object_68: THREE.Mesh
    Object_70: THREE.Mesh
    Object_72: THREE.Mesh
    Object_74: THREE.Mesh
    Object_76: THREE.Mesh
    Object_78: THREE.Mesh
    Object_80: THREE.Mesh
    Object_82: THREE.Mesh
    Object_84: THREE.Mesh
    Object_86: THREE.Mesh
    Object_88: THREE.Mesh
    Object_90: THREE.Mesh
    Object_92: THREE.Mesh
    Object_94: THREE.Mesh
    Object_96: THREE.Mesh
    Object_98: THREE.Mesh
    Object_100: THREE.Mesh
    Object_102: THREE.Mesh
    Object_104: THREE.Mesh
    Object_106: THREE.Mesh
    Object_108: THREE.Mesh
    Object_110: THREE.Mesh
    Object_112: THREE.Mesh
    Object_114: THREE.Mesh
    Object_116: THREE.Mesh
    Object_118: THREE.Mesh
    Object_120: THREE.Mesh
    Object_122: THREE.Mesh
    Object_124: THREE.Mesh
    Object_126: THREE.Mesh
    Object_128: THREE.Mesh
    Object_130: THREE.Mesh
    Object_132: THREE.Mesh
    Object_134: THREE.Mesh
    Object_136: THREE.Mesh
    Object_138: THREE.Mesh
    Object_140: THREE.Mesh
    Object_142: THREE.Mesh
    Object_144: THREE.Mesh
    Object_146: THREE.Mesh
    Object_148: THREE.Mesh
    Object_150: THREE.Mesh
    Object_152: THREE.Mesh
    Object_154: THREE.Mesh
    Object_156: THREE.Mesh
    Object_158: THREE.Mesh
    Object_160: THREE.Mesh
    Object_162: THREE.Mesh
    Object_164: THREE.Mesh
    Object_166: THREE.Mesh
    Object_168: THREE.Mesh
    Object_170: THREE.Mesh
    Object_172: THREE.Mesh
    Object_174: THREE.Mesh
    Object_176: THREE.Mesh
    Object_178: THREE.Mesh
    Object_180: THREE.Mesh
    Object_182: THREE.Mesh
    Object_184: THREE.Mesh
  }
  materials: {
    ['Material.030']: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.028']: THREE.MeshStandardMaterial
    ['Material.018']: THREE.MeshStandardMaterial
    ['Material.024']: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.020']: THREE.MeshStandardMaterial
    ['Material.025']: THREE.MeshStandardMaterial
    ['Material.027']: THREE.MeshStandardMaterial
    ['Material.015']: THREE.MeshStandardMaterial
    ['Material.017']: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.038']: THREE.MeshStandardMaterial
    ['Material.036']: THREE.MeshStandardMaterial
    ['Material.037']: THREE.MeshStandardMaterial
    ['Material.034']: THREE.MeshStandardMaterial
    ['Material.031']: THREE.MeshStandardMaterial
    ['Material.032']: THREE.MeshStandardMaterial
    ['Material.033']: THREE.MeshStandardMaterial
    ['Material.042']: THREE.MeshStandardMaterial
    ['Material.043']: THREE.MeshStandardMaterial
    ['Material.044']: THREE.MeshStandardMaterial
    ['Material.045']: THREE.MeshStandardMaterial
    ['mat0.009']: THREE.MeshStandardMaterial
    ['mat0.005']: THREE.MeshStandardMaterial
    ['mat0.015']: THREE.MeshStandardMaterial
    ['mat0.016']: THREE.MeshStandardMaterial
    ['mat0.022']: THREE.MeshStandardMaterial
    ['mat0.023']: THREE.MeshStandardMaterial
    ['mat0.024']: THREE.MeshStandardMaterial
    ['mat0.027']: THREE.MeshStandardMaterial
    ['mat0.028']: THREE.MeshStandardMaterial
    ['mat0.059']: THREE.MeshStandardMaterial
    ['mat0.041']: THREE.MeshStandardMaterial
  }
}

import path from "/models/free_fire_clocktower_freefire-transformed.glb?url";
import {Group} from "three";


export default forwardRef(function Model(props: JSX.IntrinsicElements['group'], ref: ForwardedRef<Group>) {
  const { nodes, materials } = useGLTF(path) as GLTFResult
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials['Material.030']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials['Material.009']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_8.geometry} material={materials['Material.009']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_10.geometry} material={materials['Material.007']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_12.geometry} material={materials['Material.008']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_14.geometry} material={materials['Material.002']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_16.geometry} material={materials['Material.009']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_18.geometry} material={materials['Material.009']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_20.geometry} material={materials['Material.028']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_22.geometry} material={materials['Material.018']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_24.geometry} material={materials['Material.024']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_26.geometry} material={materials['Material.001']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_28.geometry} material={materials['Material.020']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_30.geometry} material={materials['Material.025']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_32.geometry} material={materials['Material.027']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_34.geometry} material={materials['Material.028']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_36.geometry} material={materials['Material.028']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_38.geometry} material={materials['Material.028']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_40.geometry} material={materials['Material.015']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_42.geometry} material={materials['Material.025']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_44.geometry} material={materials['Material.017']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_46.geometry} material={materials['Material.004']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_48.geometry} material={materials['Material.003']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_50.geometry} material={materials['Material.005']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_52.geometry} material={materials['Material.006']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_54.geometry} material={materials['Material.028']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_56.geometry} material={materials['Material.009']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_58.geometry} material={materials['Material.028']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_60.geometry} material={materials['Material.028']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_62.geometry} material={materials['Material.025']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_64.geometry} material={materials['Material.020']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_66.geometry} material={materials['Material.010']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_68.geometry} material={materials['Material.038']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_70.geometry} material={materials['Material.036']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_72.geometry} material={materials['Material.037']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_74.geometry} material={materials['Material.020']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_76.geometry} material={materials['Material.034']} position={[18.22, 17.4, 8.29]} rotation={[Math.PI / 2, 0, 0]} scale={0.73} />
      <mesh castShadow receiveShadow geometry={nodes.Object_78.geometry} material={materials['Material.031']} position={[18.22, 17.4, 8.29]} scale={113.59} />
      <mesh castShadow receiveShadow geometry={nodes.Object_80.geometry} material={materials['Material.032']} position={[-41.66, 22.22, -40.29]} rotation={[-Math.PI, 0, 0]} scale={[-11.39, 11.39, 11.39]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_82.geometry} material={materials['Material.033']} position={[-42.88, 14.14, -22.27]} rotation={[-2.05, -1.07, -1.47]} scale={[-13.3, 13.3, 13.3]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_84.geometry} material={materials['Material.042']} position={[-42.88, 14.14, -18.24]} rotation={[1.32, -0.25, 1.8]} scale={[-13.3, 13.3, 13.3]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_86.geometry} material={materials['Material.043']} position={[78.4, 14.7, 30.02]} rotation={[1.62, -0.33, 1.81]} scale={[-13.3, 13.3, 13.3]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_88.geometry} material={materials['Material.044']} position={[84.35, 12.38, 15.44]} rotation={[2.64, -1.17, 1.3]} scale={[-13.3, 13.3, 13.3]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_90.geometry} material={materials['Material.045']} position={[81.59, 23.29, 11.96]} rotation={[-2.84, 0.04, 0.07]} scale={[-11.39, 11.39, 11.39]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_92.geometry} material={materials['Material.033']} position={[-46.91, 18.82, -15.35]} rotation={[1.32, -0.06, 1.87]} scale={[-13.3, 13.3, 13.3]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_94.geometry} material={materials['Material.032']} position={[-57.9, 14.01, -21.05]} rotation={[-2.02, 0.25, -1.17]} scale={[-13.3, 13.3, 13.3]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_96.geometry} material={materials['Material.032']} position={[-46.97, 15.47, -31.99]} rotation={[2.88, 0.17, 1.33]} scale={[-11.39, 11.39, 11.39]} />
      <mesh castShadow receiveShadow geometry={nodes.Object_98.geometry} material={materials['mat0.009']} position={[-36.74, 17.92, 0.95]} rotation={[Math.PI / 2, 0, 0]} scale={0.81} />
      <mesh castShadow receiveShadow geometry={nodes.Object_100.geometry} material={materials['mat0.009']} position={[-36.74, 17.92, 11.23]} rotation={[Math.PI / 2, 0, 0]} scale={0.81} />
      <mesh castShadow receiveShadow geometry={nodes.Object_102.geometry} material={materials['mat0.009']} position={[-36.74, 17.92, 22.5]} rotation={[Math.PI / 2, 0, 0]} scale={0.81} />
      <mesh castShadow receiveShadow geometry={nodes.Object_104.geometry} material={materials['mat0.009']} position={[-36.74, 17.92, 34.68]} rotation={[Math.PI / 2, 0, 0]} scale={0.81} />
      <mesh castShadow receiveShadow geometry={nodes.Object_106.geometry} material={materials['mat0.009']} position={[-47.8, 18.3, -37.19]} rotation={[Math.PI / 2, 0, 0]} scale={0.81} />
      <mesh castShadow receiveShadow geometry={nodes.Object_108.geometry} material={materials['mat0.005']} position={[-47.73, 18.03, -38.03]} rotation={[1.37, 0, 0.09]} scale={0.61} />
      <mesh castShadow receiveShadow geometry={nodes.Object_110.geometry} material={materials['mat0.009']} position={[-32.95, 15.89, -49.58]} rotation={[Math.PI / 2, 0, 0]} scale={0.81} />
      <mesh castShadow receiveShadow geometry={nodes.Object_112.geometry} material={materials['mat0.009']} position={[-18.12, 15.89, -49.58]} rotation={[Math.PI / 2, 0, 0]} scale={0.81} />
      <mesh castShadow receiveShadow geometry={nodes.Object_114.geometry} material={materials['mat0.009']} position={[-0.72, 15.89, -49.58]} rotation={[Math.PI / 2, 0, 0]} scale={0.81} />
      <mesh castShadow receiveShadow geometry={nodes.Object_116.geometry} material={materials['mat0.009']} position={[13.84, 15.89, -49.58]} rotation={[Math.PI / 2, 0, 0]} scale={0.81} />
      <mesh castShadow receiveShadow geometry={nodes.Object_118.geometry} material={materials['mat0.009']} position={[38.51, 15.89, -49.58]} rotation={[Math.PI / 2, 0, 0]} scale={1.13} />
      <mesh castShadow receiveShadow geometry={nodes.Object_120.geometry} material={materials['mat0.009']} position={[67.92, 15.89, -49.58]} rotation={[Math.PI / 2, 0, 0]} scale={0.81} />
      <mesh castShadow receiveShadow geometry={nodes.Object_122.geometry} material={materials['mat0.009']} position={[-28.67, 6.47, 9.22]} rotation={[Math.PI / 2, 0, 0]} scale={1.29} />
      <mesh castShadow receiveShadow geometry={nodes.Object_124.geometry} material={materials['mat0.009']} position={[67.92, 15.89, -16.69]} rotation={[Math.PI / 2, 0, 0]} scale={0.81} />
      <mesh castShadow receiveShadow geometry={nodes.Object_126.geometry} material={materials['mat0.015']} position={[67.92, 15.89, 0.78]} rotation={[Math.PI / 2, 0, 0]} scale={0.81} />
      <mesh castShadow receiveShadow geometry={nodes.Object_128.geometry} material={materials['mat0.016']} position={[67.92, 15.89, 17.31]} rotation={[Math.PI / 2, 0, 0]} scale={0.81} />
      <mesh castShadow receiveShadow geometry={nodes.Object_130.geometry} material={materials['mat0.016']} position={[67.92, 15.89, 40.64]} rotation={[Math.PI / 2, 0, 0]} scale={0.81} />
      <mesh castShadow receiveShadow geometry={nodes.Object_132.geometry} material={materials['mat0.009']} position={[57.22, 15.89, 66.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.81} />
      <mesh castShadow receiveShadow geometry={nodes.Object_134.geometry} material={materials['mat0.009']} position={[33.67, 15.89, 66.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.81} />
      <mesh castShadow receiveShadow geometry={nodes.Object_136.geometry} material={materials['mat0.009']} position={[9.05, 15.89, 66.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.81} />
      <mesh castShadow receiveShadow geometry={nodes.Object_138.geometry} material={materials['mat0.009']} position={[-23, 15.89, 66.3]} rotation={[Math.PI / 2, 0, 0]} scale={0.8} />
      <mesh castShadow receiveShadow geometry={nodes.Object_140.geometry} material={materials['mat0.022']} position={[-73.48, 22.02, 14.2]} rotation={[Math.PI / 2, 0, 0]} scale={0.4} />
      <mesh castShadow receiveShadow geometry={nodes.Object_142.geometry} material={materials['mat0.023']} position={[-67.62, 21.21, 6.13]} rotation={[1.58, 0.02, -0.01]} scale={0.53} />
      <mesh castShadow receiveShadow geometry={nodes.Object_144.geometry} material={materials['mat0.024']} position={[48.91, 20.7, 5.83]} rotation={[1.58, 0.02, -0.01]} scale={0.53} />
      <mesh castShadow receiveShadow geometry={nodes.Object_146.geometry} material={materials['mat0.024']} position={[26.17, 21.02, 84.58]} rotation={[1.58, 0.02, -0.01]} scale={0.53} />
      <mesh castShadow receiveShadow geometry={nodes.Object_148.geometry} material={materials['mat0.024']} position={[-69.97, 21.22, 80.4]} rotation={[1.58, 0.02, -0.01]} scale={0.53} />
      <mesh castShadow receiveShadow geometry={nodes.Object_150.geometry} material={materials['mat0.027']} position={[-39.43, 18.39, -7.73]} rotation={[Math.PI / 2, 0, 0]} scale={2.48} />
      <mesh castShadow receiveShadow geometry={nodes.Object_152.geometry} material={materials['mat0.028']} position={[-37.42, 19.11, -34.53]} rotation={[Math.PI / 2, 0, 0]} scale={2.48} />
      <mesh castShadow receiveShadow geometry={nodes.Object_154.geometry} material={materials['mat0.028']} position={[40.01, 20.39, -29.18]} rotation={[Math.PI / 2, 0, 0]} scale={2.48} />
      <mesh castShadow receiveShadow geometry={nodes.Object_156.geometry} material={materials['mat0.009']} position={[40.01, 20.39, 60.24]} rotation={[Math.PI / 2, 0, 0]} scale={2.48} />
      <mesh castShadow receiveShadow geometry={nodes.Object_158.geometry} material={materials['mat0.009']} position={[70.89, 17.04, 43.46]} rotation={[Math.PI / 2, 0, 0]} scale={2.48} />
      <mesh castShadow receiveShadow geometry={nodes.Object_160.geometry} material={materials['mat0.009']} position={[-45.11, 19.12, 42.17]} rotation={[Math.PI / 2, 0, 0]} scale={2.48} />
      <mesh castShadow receiveShadow geometry={nodes.Object_162.geometry} material={materials['mat0.016']} position={[-48.99, 18.6, 2.19]} rotation={[Math.PI / 2, 0, 0]} scale={3.15} />
      <mesh castShadow receiveShadow geometry={nodes.Object_164.geometry} material={materials['mat0.016']} position={[78.11, 18.6, 2.19]} rotation={[Math.PI / 2, 0, 0]} scale={3.15} />
      <mesh castShadow receiveShadow geometry={nodes.Object_166.geometry} material={materials['mat0.059']} position={[100.21, 14.24, 34.01]} rotation={[Math.PI / 2, 0, 0]} scale={1.29} />
      <mesh castShadow receiveShadow geometry={nodes.Object_168.geometry} material={materials['mat0.028']} position={[59.97, 19.11, -34.53]} rotation={[Math.PI / 2, 0, 0]} scale={2.48} />
      <mesh castShadow receiveShadow geometry={nodes.Object_170.geometry} material={materials['mat0.009']} position={[54.17, 14.52, -53.48]} rotation={[Math.PI / 2, 0, 0]} scale={1.13} />
      <mesh castShadow receiveShadow geometry={nodes.Object_172.geometry} material={materials['mat0.009']} position={[24.32, 17.83, -46.55]} rotation={[Math.PI / 2, 0, 0]} scale={1.13} />
      <mesh castShadow receiveShadow geometry={nodes.Object_174.geometry} material={materials['mat0.009']} position={[-58.08, 14.29, -18.48]} rotation={[Math.PI / 2, 0, 0]} scale={1.13} />
      <mesh castShadow receiveShadow geometry={nodes.Object_176.geometry} material={materials['mat0.009']} position={[50.67, 13.79, -18.94]} rotation={[Math.PI / 2, 0, 0]} scale={1.13} />
      <mesh castShadow receiveShadow geometry={nodes.Object_178.geometry} material={materials['mat0.041']} position={[92.06, 9.02, -17.75]} rotation={[Math.PI / 2, 0, 0]} scale={1.13} />
      <mesh castShadow receiveShadow geometry={nodes.Object_180.geometry} material={materials['mat0.009']} position={[-10.51, 15.89, -49.58]} rotation={[Math.PI / 2, 0, 0]} scale={0.81} />
      <mesh castShadow receiveShadow geometry={nodes.Object_182.geometry} material={materials['mat0.009']} position={[-28.13, 15.89, -49.58]} rotation={[Math.PI / 2, 0, 0]} scale={0.81} />
      <mesh castShadow receiveShadow geometry={nodes.Object_184.geometry} material={materials['mat0.009']} position={[3.63, 16.84, -35.69]} rotation={[Math.PI / 2, 0, 0]} scale={0.81} />
    </group>
  )
});

useGLTF.preload(path)
